replicaCount: 1

image:
  repository: ghcr.io/cliffeh/quartr
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: false
  ingressClassName: ""
  tls:
    enabled: true
    hosts:
      - argocd

nameOverride: ""
fullnameOverride: ""

env:
  QUARTR_ENV: "production"
