{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "quartr.fullname" . }}
  labels:
    {{- include "quartr.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  defaultBackend:
    service:
      name: {{ include "quartr.fullname" . }}
      port:
        number: {{ .Values.service.port }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts: {{ .Values.ingress.tls.hosts }}
  {{- end }}
{{- end }}
