name: Run Tests

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "tests/**"
      - "Makefile"
      - "pyproject.toml"
      - ".github/workflows/pr-test.yaml"

  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "tests/**"
      - "Makefile"
      - "pyproject.toml"
      - ".github/workflows/pr-test.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Create virtual environment and install dependencies
        run: make venv
    
      - name: Lint code
        run: |
            echo "Running linters..." >> $GITHUB_STEP_SUMMARY
            make lint >> $GITHUB_STEP_SUMMARY

      - name: Run tests and generate a coverage report
        run: |
            echo "Running tests..." >> $GITHUB_STEP_SUMMARY
            make coverage-md >> $GITHUB_STEP_SUMMARY
